config/config.go, go.mod, payload/payload.go, report/pdf.go, report/report.go, testcase/testcase.go
More refactoring for report keys, please check that it works before merge. Anyways it can give your more ideas.
=> Report keys replaced to struct type

Dockerfile, README.md, main.go
Changed to lightweight alpine image for docker
=> Dockerfile changed to alpine usage

config/config.go, main.go, payload/payload.go
Merge with the branch for HTTP Cookies support
=> Following cookies

internal/data/test/pdf.go
Added test case column to "bypasses in details" and "unresolved test cases" tables in pdf report.
Fixed output of payload specials chars in pdf report.
Fixed output of payload whose length exceeds the cell size.
=> Update of PDF Report

internal/data/test/load.go
@dnkolegov check it, please. Based on the httpworkers small review.
=> Fix: testCases loading and path processing

README.md, internal/data/test/pdf.go
This PR includes bugfixes and documentation updates.
Bugfix:
1. Case when we have only one chart in PDF (e.g. when we use `--testSet` or `--testCase` flags to include/exclude tests)
2. Case when we don't have results (e.g. zeroes for some positive/negative groups, only negative, only positive test sets) to build the plot in a PDF 
2. Little calculation fixes: negative cases, positiveve cases (exclude positive cases from negative, and vice versa. Separated)
Documentation:
1. Build instruction
2. CLI output
3. Other modifications
=> Fix issues, usage bugs. Update README.

cmd/main.go, internal/data/config/config.go
=> Set `url` as required cli option

internal/payload/encoder/base64.go, internal/payload/encoder/encoder.go, internal/payload/encoder/grpc.go, internal/payload/encoder/jsunicode.go, internal/payload/encoder/plain.go, internal/payload/encoder/url.go, internal/payload/encoder/xmlentity.go, internal/scanner/scanner.go, tests/integration/config/config.go
Remove unnecessary reference from the value returned from the GetName() function.
=> Change Encoder interface

Makefile, cmd/main.go, internal/report/pdf.go
=> Fix issue 105

testcases/community/community-sqli.yml, testcases/owasp/path-traversal.yml
Two ptrav payloads changed to prevent status 400.
One incorrect community-sqli payload removed.
=> testcases update

README.md, cmd/main.go, internal/config/config.go, internal/scanner/grpc_client.go, internal/scanner/scanner.go, tests/integration/config/config.go, tests/integration/gotestwaf_test.go, tests/integration/waf/grpc.go, tests/integration/waf/waf.go
Added CLI option for specify gRPC server port.
Fixed integration tests for gRPC scanning.
=> Fix gRPC support

internal/scanner/http_client.go
=> Fix Host header setting

README.md, cmd/main.go, internal/config/config.go, internal/scanner/scanner.go, tests/integration/config/config.go
=> Add ability to set multiple pass status codes

.dockerignore, Dockerfile, Makefile, cmd/flags.go, cmd/main.go, internal/config/config.go, internal/scanner/http_client.go, internal/scanner/scanner.go, tests/integration/config/config.go, tests/integration/gotestwaf_test.go, tests/integration/waf/grpc.go, tests/integration/waf/waf.go
=> New option to add debug header

internal/db/helpers.go, internal/report/chart.go, internal/report/html.go, pkg/report/chart.go, pkg/report/html.go
=> Add check for NaN value for float numbers

testcases/owasp/path-traversal.yml
Have changed 
```
..\..\..\..\usr/lib\libinjection.so.6
```
to 
```
../../../../usr/lib/libc.so.6
```
=> Path Traversal, payload update

Dockerfile
unzip: can't change directory to 'inter': No such file or directory.
Looks like a problem with unzip. Solution - install the unzip package.
=> Problems with GTW docker build. Tested on Ubuntu 20.04 and Debian 10.

internal/scanner/scanner.go
In order to use --blockRegex --passRegex. 
=> Fix PassRegex on checkPass func
related to #198
=> Fix checkPass func

internal/helpers/file_move.go, internal/helpers/file_move_test.go, internal/helpers/rename.go, internal/report/html.go
=> Fix invalid cross-device link error

go.mod, go.sum, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/pipe.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/testsync.go, vendor/golang.org/x/net/http2/transport.go, vendor/modules.txt
Fixed security issue on v0.23.0.
https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2-6531285
=> Bump golang.org/x/net v0.21.0 to v0.23.0

.gitignore, misc/modsec_regression_testset_converter.rb
=> Fix `modsec_regression_testset_converter.rb`

README.md, cmd/gotestwaf/flags.go
=> Fix CLI args description

internal/scanner/scanner.go, internal/scanner/scanner_signal_handler_unix.go, internal/scanner/scanner_signal_handler_windows.go
=> Mock Windows signal handler
